# LAYOUT_LIST = ['corridor', 'five_by_five', 'mdp_test', 'multiplayer_schelling',
#                'random0', 'random1', 'random2', 'random3', 'scenario1_s',
#                'scenario2', 'scenario2_s', 'scenario3', 'scenario4',
#                'schelling', 'schelling_s', 'simple', 'simple_single',
#                'simple_tomato', 'small_corridor', 'unident', 'unident_s','large_room']

# NAME_TRANSLATION = {
#     "cramped_room": "simple",
#     "asymmetric_advantages": "unident_s",
#     "coordination_ring": "random1",
#     "forced_coordination": "random0",
#     "counter_circuit": "random3",
# }

LAYOUT_LIST = [
    "asymmetric_advantages",
    "asymmetric_advantages_tomato",
    "bonus_order_test",
    "bottleneck",
    "centre_objects",
    "centre_pots",
    "coordination_ring",
    "corridor",
    "counter_circuit",
    "counter_circuit_o_1order",
    "cramped_corridor",
    "cramped_room",
    "cramped_room_o_3orders",
    "cramped_room_single",
    "cramped_room_tomato",
    "five_by_five",
    "forced_coordination",
    "forced_coordination_tomato",
    "inverse_marshmallow_experiment",
    "large_room",
    "long_cook_time",
    "marshmallow_experiment",
    "marshmallow_experiment_coordination",
    "mdp_test",
    "multiplayer_schelling",
    "m_shaped_s",
    "pipeline",
    "scenario1_s",
    "scenario2",
    "scenario2_s",
    "scenario3",
    "scenario4",
    "schelling",
    "schelling_s",
    "simple_o",
    "simple_o_t",
    "simple_tomato",
    "small_corridor",
    "soup_coordination",
    "tutorial_0",
    "tutorial_1",
    "tutorial_2",
    "tutorial_3",
    "unident",
    "you_shall_not_pass"
]